name: fluxpart-nn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python  # Change this to desired Python version
  - ipython
  - notebook
  - matplotlib
  - pandas
  - scikit-learn
  - numpy
  - scipy
  - seaborn
  - statsmodels
  - jupyterlab
  - nodejs
  - xeus-python
  - black
  - flake8
  - pytest
  - jax
  - jaxlib
  - pyyaml
  - pathlib
  - optax
  - chex=0.1.5
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkit
  - torchaudio
  - pip:
      - xgboost==1.7.5
      - SkillMetrics